name: staffin_softwares
version: 1.0.0+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts:
  http:
  get: 4.6.6
  get_storage:
  image_picker:
  flutter_datetime_picker_plus: ^2.1.0
  firebase_core:
  firebase_auth:
  firebase_messaging:
  google_maps_flutter: ^2.5.0
  geolocator:
  location: ^5.0.3
  fluttertoast:
  flutter_spinkit: ^5.2.0
  loader_overlay: ^2.3.2
  table_calendar:
  flutter_svg: ^2.0.9
  country_picker: ^2.0.22
  pinput: ^3.0.1
  signature:
  path_provider: ^2.1.1
  intl:
  url_launcher: ^6.2.2
  flutter_widget_from_html: ^0.14.9
  flutter_background_service: ^5.0.5
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0
  responsive_sizer: ^3.3.0+1
  permission_handler: ^11.3.0
  flutter_launcher_icons: ^0.13.1
  calendar_date_picker2: ^0.5.5
  omni_datetime_picker: ^1.0.9
  toggle_switch: ^2.1.0
  flutter_pdfview: ^1.3.2
  flutter_cached_pdfview: ^0.4.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splashAndLogo/fleet_focus_logo.png"

flutter: 
  uses-material-design: true
  assets:
   - assets/
   - assets/splashAndLogo/
   - assets/splashAndLogo/Mask group.png
   - assets/auth_images/
   - assets/dashboard_images/
   - assets/daily_login/
   - assets/auth_images/loginImage.png

