// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgODIatOe3iRdBPKPAENtyTi_FBlOyV2A',
    appId: '1:29565148878:web:2852922337004e3575ba9f',
    messagingSenderId: '29565148878',
    projectId: 'staffinsoftware-d4ec5',
    authDomain: 'staffinsoftware-d4ec5.firebaseapp.com',
    storageBucket: 'staffinsoftware-d4ec5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn20ff6Q2d4WAEGROE8dMjUa0-P8F6Jcs',
    appId: '1:29565148878:android:3c972522e9a70b1575ba9f',
    messagingSenderId: '29565148878',
    projectId: 'staffinsoftware-d4ec5',
    storageBucket: 'staffinsoftware-d4ec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtSCO03dQHeYbMe_wZle5pTUiUgYFjo0',
    appId: '1:29565148878:ios:9d49a2aa388f139975ba9f',
    messagingSenderId: '29565148878',
    projectId: 'staffinsoftware-d4ec5',
    storageBucket: 'staffinsoftware-d4ec5.appspot.com',
    iosBundleId: 'com.example.staffinSoftwares',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOtSCO03dQHeYbMe_wZle5pTUiUgYFjo0',
    appId: '1:29565148878:ios:96e78a0360730adb75ba9f',
    messagingSenderId: '29565148878',
    projectId: 'staffinsoftware-d4ec5',
    storageBucket: 'staffinsoftware-d4ec5.appspot.com',
    iosBundleId: 'com.example.staffinSoftwares.RunnerTests',
  );
}
